AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function ListBucketsCommand.
Resources:
  generatereport:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3        

  healthcheck:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  initdb:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  ordermanagement:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  processpayment:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  sendnotification:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  updateinventory:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Role: arn:aws:iam::227560787770:role/LabRole
      Handler: lambda_function.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS Region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3