AWSTemplateFormatVersion: '2010-09-09'
Description: VPC function.
Resources:
  Function1:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function2:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: health_check.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function3:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: init_db.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function4:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: order_management.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function5:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: process_payment.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function6:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: send_notification.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3

  Function7:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.handler
      Role: arn:aws:iam::227560787770:role/LabRole
      Code:
        S3Bucket: amzn-s3-lambda-bucket-342
        S3Key: update_inventory.zip
      Runtime: python3.11
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0dc37b86e72ef28ab
        SubnetIds:
          - subnet-0634f9388bdabd357
          - subnet-0e154a155d82a54f3