AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucketorder:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 120
                StorageClass: GLACIER
      Tags:
        - Key: 'Name'
          Value: 'techno-orders-keefa-26'
          
  S3Bucketlogs:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 120
            Transitions:
              - TransitionInDays: 14
                StorageClass: GLACIER
      Tags:
        - Key: 'Name'
          Value: 'techno-logs-keefa-26'